package org.example.entity.enums;

public enum Position {
    DRIVER, MANAGER, OWNER, ACCOUNTANT, LEGAL_ADVISOR, MARKETING_SALES, LOGISTIC, HR, MECHANIC, OFFICE_ASSISTANT, WAREHOUSE_OPERATOR, OTHER
}
